FROM ubuntu:latest


RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y


# Install curl and build essentials
RUN apt-get update && apt-get install -y curl build-essential

# Install Rust
# We use rustup to install Rust, which makes it easy to manage and update
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y


ENV PATH="/root/.cargo/bin:${PATH}"
